repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        pass_filenames: false
        files: $(git diff --name-only master HEAD -- "*.py" | xargs)
        args: [$(git diff --name-only master HEAD -- "*.py" | xargs)]
