repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [git diff --name-only master HEAD -- "*.py" | xargs]

#-   repo: https://github.com/pre-commit/mirrors-eslint
#    rev: v8.42.0
#    hooks:
#        - id: eslint
