name: pre-commit

on:
  pull_request:
    branches: [master]
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get changed files
      id: changed-files
      run: |
        TOKEN="${{ secrets.GITHUB_TOKEN }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
        API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files"
        CHANGED_FILES=$(curl -s -H "Authorization: Bearer ${TOKEN}" "${API_URL}" | jq -r '.[].filename')
        echo "::set-output name=changed_files::${CHANGED_FILES}"

    - name: Display Changed Files
      run: |
        echo "Changed files:"
        echo "${{ steps.changed-files.outputs.changed_files }}"

    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: flake8 --files=${{ steps.changed-files.outputs.changed_files }}