name: pre-commit

on:
  pull_request:
    branches: [master]
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit on changed files
      run: pre-commit run --from-ref ${{ github.base_ref }} --to-ref ${{ github.head_ref }} --files $(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }})